In [2]:
import pandas as pd
import numpy as np
import re
import math

In [3]:
# Wilcoxon signed-rank test
from numpy.random import seed
from numpy.random import randn
from scipy.stats import wilcoxon

In [4]:
import os,sys,inspect
currentdir = os.path.dirname(os.path.abspath(inspect.getfile(inspect.currentframe())))
parentdir = os.path.dirname(currentdir)
sys.path.insert(0,parentdir)

In [5]:
from statistic import Statistic

In [6]:
# If probability < alfa = different values 

def wilcoxon_test(data1, data2, alpha= 0.05):
    stat, p = wilcoxon(data1, data2)
    print('Statistics=%.3f, p=%.3f, thereshold=%.3f' % (stat, p,alpha))
        
    if p > alpha:
        print('Same distribution (fail to reject H0)')
    else:
        print('Different distribution (reject H0)')
        
        

In [73]:
data2 = '7.41	11.11	13.32	15.03	17.23	20.55	21.89	23.78	38.23'.split('\t')
data2 = [ float(d) for d in data2 ]
data2

[7.41, 11.11, 13.32, 15.03, 17.23, 20.55, 21.89, 23.78, 38.23]

In [74]:
# generate two independent samples
data1 = 5 * randn(100) + 50
data2 = 5 * randn(100) + 51

In [75]:
data1 = [9.07, 14.38, 15.73, 19.90, 22.01, 23.56, 25.79, 30.69, 42.82]
data2 = [7.20, 17.02, 18.59, 19.83, 20.96, 21.31, 23.38, 26.68, 42.36]
data3 = [7.41, 11.11, 13.32, 15.03, 17.23, 20.55, 21.89, 23.78, 38.23]

In [78]:
# compare samples
wilcoxon_test(data1, data2)

Statistics=15.000, p=0.374, thereshold=0.050
Same distribution (fail to reject H0)


In [79]:
wilcoxon_test(data1, data3)

Statistics=0.000, p=0.008, thereshold=0.050
Different distribution (reject H0)


In [80]:
wilcoxon_test(data2, data3)

Statistics=1.000, p=0.011, thereshold=0.050
Different distribution (reject H0)


In [ ]:
# Compare data from covid deaths from USA

In [6]:
path_covid = parentdir + '/data_covid/'
path_2020 = path_covid + 'Provisional_COVID-19_Death_Counts_by_Week_Ending_Date_and_State.csv'
path_2019_2020 = path_covid + 'VSRR_-_State_and_National_Provisional_Counts_for_Live_Births__Deaths__and_Infant_Deaths.csv'
df_cov_2020 = pd.read_csv(path_2020  , dtype=str)
df_2019_2020 = pd.read_csv(path_2019_2020  , dtype=str)

In [7]:
list(df_cov_2020)

['Data as of',
 'Start week',
 'End Week',
 'Group',
 'State',
 'Indicator',
 'COVID-19 Deaths',
 'Total Deaths',
 'Percent of Expected Deaths',
 'Pneumonia Deaths',
 'Pneumonia and COVID-19 Deaths',
 'Influenza Deaths',
 'Pneumonia, Influenza, or COVID-19 Deaths',
 'Footnote']

In [8]:
df_cov_2020.loc[:,'Total Deaths'] = pd.to_numeric(df_cov_2020['Total Deaths'], errors="coerce")

In [93]:
# Statistic.get_table(df_cov_2020, 'State')

In [9]:
df_US = df_cov_2020[df_cov_2020.State == 'United States'].copy()

In [10]:
df_US.shape

(36, 14)

In [11]:
data1 = df_US['Total Deaths'].values[:10]
data2 = df_US['Total Deaths'].values[10:20]
data3 = df_US['Total Deaths'].values[20:30]

In [12]:
df = pd.DataFrame(data={'d1': data1, 'd2':data2, 'd3':data3})
df

d1       d2       d3
0  58606.0  78915.0  57654.0
1  59314.0  76573.0  58134.0
2  58723.0  73663.0  59381.0
3  58761.0  69074.0  61319.0
4  59193.0  66655.0  62350.0
5  59600.0  64312.0  63005.0
6  58571.0  61420.0  62383.0
7  59109.0  59455.0  62189.0
8  62894.0  58659.0  61369.0
9  72154.0  57758.0  58977.0

In [13]:
wilcoxon_test(data1, data2, alpha=0.1)

Statistics=10.000, p=0.074, thereshold=0.100
Different distribution (reject H0)


In [15]:
wilcoxon_test(data2, data3,  alpha=0.1)

Statistics=12.000, p=0.114, thereshold=0.100
Same distribution (fail to reject H0)


In [16]:
wilcoxon_test(data1, data3, alpha=0.1)

Statistics=19.000, p=0.386, thereshold=0.100
Same distribution (fail to reject H0)


In [17]:
df_2019_2020.head()

State  Year     Month   Period              Indicator Data Value
0  UNITED STATES  2019   January  Monthly  Number of Live Births     311000
1  UNITED STATES  2019  February  Monthly  Number of Live Births     280000
2  UNITED STATES  2019     March  Monthly  Number of Live Births     304000
3  UNITED STATES  2019     April  Monthly  Number of Live Births     299000
4  UNITED STATES  2019       May  Monthly  Number of Live Births     316000

In [18]:
df_2019_2020.loc[:,'Data Value'] = pd.to_numeric(df_2019_2020.loc[:,'Data Value'], errors="coerce")

In [19]:
mask = (df_2019_2020.State == 'UNITED STATES') & (df_2019_2020.Indicator == 'Number of Deaths')
df_usa = df_2019_2020[mask].copy()

In [20]:
mask = (df_usa.Year == '2020') & (df_usa.Period == 'Monthly')
df_usa_2020 = df_usa[mask]
df_usa_2020

State  Year     Month   Period         Indicator  Data Value
27  UNITED STATES  2020   January  Monthly  Number of Deaths      263000
28  UNITED STATES  2020  February  Monthly  Number of Deaths      243000
29  UNITED STATES  2020     March  Monthly  Number of Deaths      268000

In [21]:
mask = (df_usa.Year == '2019') & (df_usa.Period == 'Monthly')
df_usa_2019 = df_usa[mask]
df_usa_2019

State  Year      Month   Period         Indicator  Data Value
15  UNITED STATES  2019    January  Monthly  Number of Deaths      258000
16  UNITED STATES  2019   February  Monthly  Number of Deaths      233000
17  UNITED STATES  2019      March  Monthly  Number of Deaths      255000
18  UNITED STATES  2019      April  Monthly  Number of Deaths      235000
19  UNITED STATES  2019        May  Monthly  Number of Deaths      237000
20  UNITED STATES  2019       June  Monthly  Number of Deaths      225000
21  UNITED STATES  2019       July  Monthly  Number of Deaths      229000
22  UNITED STATES  2019     August  Monthly  Number of Deaths      227000
23  UNITED STATES  2019  September  Monthly  Number of Deaths      223000
24  UNITED STATES  2019    October  Monthly  Number of Deaths      238000
25  UNITED STATES  2019   November  Monthly  Number of Deaths      239000
26  UNITED STATES  2019   December  Monthly  Number of Deaths      256000

In [22]:
col_names = ['Year', 'Month', 'Data Value']
df = pd.merge(df_usa_2020[col_names], df_usa_2019[col_names], how='left', on=['Month'])

In [23]:
df['percent'] = round((df['Data Value_x']/df['Data Value_y'] -1) *100,2)
df

Year_x     Month  Data Value_x Year_y  Data Value_y  percent
0   2020   January        263000   2019        258000     1.94
1   2020  February        243000   2019        233000     4.29
2   2020     March        268000   2019        255000     5.10

In [24]:
wilcoxon_test(df['Data Value_y'].values,df['Data Value_x'].values, alpha=0.11)

Statistics=0.000, p=0.109, thereshold=0.110
Different distribution (reject H0)


/home/sergey/anaconda3/lib/python3.6/site-packages/scipy/stats/morestats.py:2778: UserWarning: Warning: sample size too small for normal approximation.
  warnings.warn("Warning: sample size too small for normal approximation.")


In [25]:
mask = df_usa.Period == 'Monthly'
dt = df_usa[mask].copy()
dt

State  Year      Month   Period         Indicator  Data Value
15  UNITED STATES  2019    January  Monthly  Number of Deaths      258000
16  UNITED STATES  2019   February  Monthly  Number of Deaths      233000
17  UNITED STATES  2019      March  Monthly  Number of Deaths      255000
18  UNITED STATES  2019      April  Monthly  Number of Deaths      235000
19  UNITED STATES  2019        May  Monthly  Number of Deaths      237000
20  UNITED STATES  2019       June  Monthly  Number of Deaths      225000
21  UNITED STATES  2019       July  Monthly  Number of Deaths      229000
22  UNITED STATES  2019     August  Monthly  Number of Deaths      227000
23  UNITED STATES  2019  September  Monthly  Number of Deaths      223000
24  UNITED STATES  2019    October  Monthly  Number of Deaths      238000
25  UNITED STATES  2019   November  Monthly  Number of Deaths      239000
26  UNITED STATES  2019   December  Monthly  Number of Deaths      256000
27  UNITED STATES  2020    January  Monthly  Number of Deaths      263000
28  UNITED STATES  2020   February  Monthly  Number of Deaths      243000
29  UNITED STATES  2020      March  Monthly  Number of Deaths      268000

In [26]:
data1 = dt['Data Value'].values[:7]
data2 = dt['Data Value'].values[8:15]

In [27]:
wilcoxon_test(data1,data2, alpha=0.11)

Statistics=8.000, p=0.310, thereshold=0.110
Same distribution (fail to reject H0)


In [28]:
df_2019_2020.head()

State  Year     Month   Period              Indicator  Data Value
0  UNITED STATES  2019   January  Monthly  Number of Live Births      311000
1  UNITED STATES  2019  February  Monthly  Number of Live Births      280000
2  UNITED STATES  2019     March  Monthly  Number of Live Births      304000
3  UNITED STATES  2019     April  Monthly  Number of Live Births      299000
4  UNITED STATES  2019       May  Monthly  Number of Live Births      316000

In [29]:
mask = (df_2019_2020.State != 'UNITED STATES') & (df_2019_2020.Indicator == 'Number of Deaths')
df_state = df_2019_2020[mask].copy()

In [30]:
mask = df_state.Year == '2020'
df_state_2020 = df_state[mask]
df_state_2020.head()

State  Year    Month   Period         Indicator  Data Value
714     ALABAMA  2020  January  Monthly  Number of Deaths        4799
715      ALASKA  2020  January  Monthly  Number of Deaths         434
716     ARIZONA  2020  January  Monthly  Number of Deaths        5767
717    ARKANSAS  2020  January  Monthly  Number of Deaths        2986
718  CALIFORNIA  2020  January  Monthly  Number of Deaths       25624

In [31]:
mask = df_state.Year == '2019'
df_state_2019 = df_state[mask]
df_state_2019.head()

State  Year    Month   Period         Indicator  Data Value
90     ALABAMA  2019  January  Monthly  Number of Deaths        4904
91      ALASKA  2019  January  Monthly  Number of Deaths         417
92     ARIZONA  2019  January  Monthly  Number of Deaths        5655
93    ARKANSAS  2019  January  Monthly  Number of Deaths        2974
94  CALIFORNIA  2019  January  Monthly  Number of Deaths       24885

In [32]:
col_names = ['Year', 'State','Month', 'Data Value']
df_states = pd.merge(df_state_2020[col_names], df_state_2019[col_names], how='left', on=['State','Month'])
df_states['percent'] = round((df_states['Data Value_x']/df_states['Data Value_y'] -1) *100,2)
df_states.sort_values(by=['State','Month'], inplace=True)
df_states.head(9)

Year_x    State     Month  Data Value_x Year_y  Data Value_y  percent
52    2020  ALABAMA  February          4690   2019          4416     6.20
0     2020  ALABAMA   January          4799   2019          4904    -2.14
104   2020  ALABAMA     March          4804   2019          4765     0.82
53    2020   ALASKA  February           375   2019           373     0.54
1     2020   ALASKA   January           434   2019           417     4.08
105   2020   ALASKA     March           364   2019           420   -13.33
54    2020  ARIZONA  February          5375   2019          4841    11.03
2     2020  ARIZONA   January          5767   2019          5655     1.98
106   2020  ARIZONA     March          5848   2019          5484     6.64

In [33]:
data1 = df_states['Data Value_x'].values
data2 = df_states['Data Value_y'].values
wilcoxon_test(data1,data2, alpha=0.11)

Statistics=1918.500, p=0.000, thereshold=0.110
Different distribution (reject H0)


In [34]:
df_states[['Data Value_x','Data Value_y']].describe()

Data Value_x  Data Value_y
count    156.000000    156.000000
mean    5015.916667   4827.224359
std     5102.440011   4873.510146
min      364.000000    373.000000
25%     1369.000000   1399.750000
50%     3680.500000   3537.500000
75%     6070.000000   5828.000000
max    25624.000000  24885.000000

In [35]:
data1 = df_states['Data Value_x'].values
data2 = df_states['Data Value_y'].values
wilcoxon_test(data1,data2, alpha=0.11)

Statistics=1918.500, p=0.000, thereshold=0.110
Different distribution (reject H0)


In [36]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3 entries, 0 to 2
Data columns (total 6 columns):
Year_x          3 non-null object
Month           3 non-null object
Data Value_x    3 non-null int64
Year_y          3 non-null object
Data Value_y    3 non-null int64
percent         3 non-null float64
dtypes: float64(1), int64(2), object(3)
memory usage: 168.0+ bytes


In [37]:
df.describe(include='all')

Year_x     Month   Data Value_x Year_y   Data Value_y   percent
count       3         3       3.000000      3       3.000000  3.000000
unique      1         3            NaN      1            NaN       NaN
top      2020  February            NaN   2019            NaN       NaN
freq        3         1            NaN      3            NaN       NaN
mean      NaN       NaN  258000.000000    NaN  248666.666667  3.776667
std       NaN       NaN   13228.756555    NaN   13650.396820  1.641351
min       NaN       NaN  243000.000000    NaN  233000.000000  1.940000
25%       NaN       NaN  253000.000000    NaN  244000.000000  3.115000
50%       NaN       NaN  263000.000000    NaN  255000.000000  4.290000
75%       NaN       NaN  265500.000000    NaN  256500.000000  4.695000
max       NaN       NaN  268000.000000    NaN  258000.000000  5.100000

In [7]:
data1 = [24,12,42,30,40,55,50,52,50,22,33,78,79,25,28,16,17,12,25]
data2 = [22,12,41,31,32,44,50,32,32,21,34,56,78,23,22,12,16,18,25]
arr = []
for i in range(len(data1)):
    diff = data1[i] - data2[i]
    diff_module = abs(diff)
    arr.append(diff_module)
arr.sort()
arr = np.array(arr)    
arr

array([ 0,  0,  0,  1,  1,  1,  1,  1,  1,  2,  2,  4,  6,  6,  8, 11, 18,
       20, 22])

In [9]:
arr = np.ravel(np.asarray(arr))
algo = 'quicksort'
sorter = np.argsort(arr, kind=algo)


In [10]:
sorter

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8, 10,  9, 11, 12, 13, 14, 15, 16,
       17, 18])

In [12]:
inv = np.empty(sorter.size, dtype=np.intp)
inv[sorter] = np.arange(sorter.size, dtype=np.intp)
inv

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8, 10,  9, 11, 12, 13, 14, 15, 16,
       17, 18])

In [16]:
arr = arr[sorter]
arr

array([ 0,  0,  0,  1,  1,  1,  1,  1,  1,  2,  2,  4,  6,  6,  8, 11, 18,
       20, 22])

In [18]:
obs = np.r_[True, arr[1:] != arr[:-1]]
obs


array([ True, False, False,  True, False, False, False, False, False,
        True, False,  True,  True, False,  True,  True,  True,  True,
        True])

numpy.ndarray

In [20]:
dense = obs.cumsum()[inv]
dense

array([ 1,  1,  1,  2,  2,  2,  2,  2,  2,  3,  3,  4,  5,  5,  6,  7,  8,
        9, 10])

In [21]:
count = np.r_[np.nonzero(obs)[0], len(obs)]
count

array([ 0,  3,  9, 11, 12, 14, 15, 16, 17, 18, 19])

In [23]:
(count[dense] + count[dense - 1] + 1)/2

array([ 2. ,  2. ,  2. ,  6.5,  6.5,  6.5,  6.5,  6.5,  6.5, 10.5, 10.5,
       12. , 13.5, 13.5, 15. , 16. , 17. , 18. , 19. ])

In [98]:
arr.sort()
start_id = 0
elem = arr[0]
range_dict = {}
for i in range(len(arr)):
    if elem != arr[i]:
        range_dict[elem] = (start_id + i + 1)/2
        start_id = i
        elem = arr[i]
    if i == len(arr) - 1:
        elem = arr[i]
        range_dict[elem] = (start_id + i) / 2 + 1

In [75]:
# reiting = []
# for i in range(len(data1)):
#     diff = data1[i] - data2[i]
#     diff_module = abs(diff)
#     v = range_dict[diff_module]
#     reiting.append(v)
# reiting    

In [100]:
r_plus = 0 
r_minus = 0
n = 0
for i in range(len(data1)):
    diff = data1[i] - data2[i]
    diff_module = abs(diff)
    if diff_module >0:
        n += 1
    try:    
        if diff > 0 :
            r_plus += range_dict[diff_module]*diff_module
        elif diff < 0:
            r_minus += range_dict[diff_module]*diff_module
    except:
        print('diff_module= {}'.format(diff_module))

T = min(r_plus, r_minus)#w        

mn = n *(n +1)/4        #mw
se = n * (n +1) * (2*n +1)/24 #dw
z = (T -mn)/math.sqrt(se)
z

1.3444279939870498

In [101]:
prob = 2. * distributions.norm.sf(abs(z))
prob

0.17881002646274535

In [102]:
T

94.0

In [103]:
wilcoxon_test(data1, data2, alpha=0.1)

Statistics=17.500, p=0.009, thereshold=0.100
Different distribution (reject H0)


In [88]:
wilcoxon(data1, data2)

WilcoxonResult(statistic=17.5, pvalue=0.008599204710374191)

In [70]:
from scipy.stats import distributions

In [72]:
prob = 2. * distributions.norm.sf(abs(z))
prob

0.06640776501248748

In [251]:
range_dict

{1: 1.5, 2: 4.0, 4: 6.0}

In [242]:
d

{4: 1, 1: 2, 2: 2}

In [311]:
arr

[2, 2, 3, 4, 6, 7, 7, 9]

In [195]:
w

2686

In [197]:
mw

6045.0

In [212]:
dw

313332.5

In [205]:
z

-6.000774154243814